// Package models defines shared data structures used across the Chart Analyzer platform.
package models

import "time"

// Signal represents a trading signal generated by an AnalysisRule.
type Signal struct {
	Symbol    string    `json:"symbol"`    // 종목 심볼 (예: "BTCUSDT", "AAPL")
	Timeframe string    `json:"timeframe"` // 타임프레임 (예: "1H", "4H", "1D", "1W")
	Rule      string    `json:"rule"`      // 신호를 생성한 룰 이름
	Direction string    `json:"direction"` // "LONG" | "SHORT" | "NEUTRAL"
	Score     float64   `json:"score"`     // 룰 강도 × TF 가중치
	Message   string    `json:"message"`   // 사람이 읽을 수 있는 신호 설명
	CreatedAt time.Time `json:"created_at"`
}

// OHLCV represents a single candlestick bar.
type OHLCV struct {
	Symbol    string    `json:"symbol"`
	Timeframe string    `json:"timeframe"`
	OpenTime  time.Time `json:"open_time"`
	Open      float64   `json:"open"`
	High      float64   `json:"high"`
	Low       float64   `json:"low"`
	Close     float64   `json:"close"`
	Volume    float64   `json:"volume"`
}

// AnalysisContext is passed to every AnalysisRule.Analyze() call.
// It provides pre-computed indicators and OHLCV data for each timeframe.
type AnalysisContext struct {
	Symbol     string
	Timeframes map[string][]OHLCV // key: "1H" | "4H" | "1D" | "1W"
	Indicators map[string]float64 // key: "RSI_14", "EMA_200", ...
}
