symbols:
    crypto:
        - symbol: BTCUSDT
          exchange: binance
          enabled: true
        - symbol: ETHUSDT
          exchange: binance
          enabled: true
    stocks:
        - symbol: TSLA
          exchange: nasdaq
          enabled: true
        - symbol: SPY
          exchange: nyse
          enabled: true
timeframes:
    - 1W
    - 1D
    - 4H
    - 1H
