// Package pinescript generates TradingView Pine Script v5 code from analysis rules.
package pinescript

import (
	"fmt"
	"strings"
)

// Generate returns a Pine Script v5 indicator script for the given rule name.
// winRate is 0-100 (percent), avgRR is the average risk-reward ratio.
// Returns an error if the rule is unknown.
func Generate(ruleName string, winRate, avgRR float64) (string, error) {
	gen, ok := generators[ruleName]
	if !ok {
		return "", fmt.Errorf("unknown rule: %s", ruleName)
	}
	header := fmt.Sprintf(
		"// Generated by Chartter\n// Rule: %s | Backtest WinRate: %.1f%% | AvgRR: %.2f\n",
		ruleName, winRate, avgRR,
	)
	return header + "\n" + strings.TrimSpace(gen()) + "\n", nil
}

// SupportedRules returns the list of rules that have Pine Script templates.
func SupportedRules() []string {
	names := make([]string, 0, len(generators))
	for k := range generators {
		names = append(names, k)
	}
	return names
}

var generators = map[string]func() string{
	"ict_fair_value_gap":          genFVG,
	"ict_order_block":             genOrderBlock,
	"ict_liquidity_sweep":         genLiquiditySweep,
	"rsi_overbought_oversold":     genRSIOBOS,
	"rsi_divergence":              genRSIDivergence,
	"support_resistance_breakout": genSRBreakout,
	"wyckoff_accumulation":        genWyckoffAccumulation,
	"wyckoff_distribution":        genWyckoffDistribution,
	"fibonacci_confluence":        genFibonacci,
}

func genFVG() string {
	return `
//@version=5
indicator("ICT Fair Value Gap", overlay=true, max_boxes_count=200)

showBull = input.bool(true, "Bullish FVG")
showBear = input.bool(true, "Bearish FVG")

// Bullish FVG: current low > high two bars ago
bullFVG = low > high[2]
// Bearish FVG: current high < low two bars ago
bearFVG = high < low[2]

if showBull and bullFVG
    box.new(bar_index[2], low, bar_index, high[2],
            bgcolor=color.new(color.green, 85),
            border_color=color.new(color.green, 50),
            border_width=1)

if showBear and bearFVG
    box.new(bar_index[2], low[2], bar_index, high,
            bgcolor=color.new(color.red, 85),
            border_color=color.new(color.red, 50),
            border_width=1)
`
}

func genOrderBlock() string {
	return `
//@version=5
indicator("ICT Order Block", overlay=true, max_boxes_count=200)

lookback = input.int(20, "Box Extend (bars)", minval=1)

// Bullish OB: bearish candle immediately before a bullish move
bullishOB = close[1] < open[1] and close > open
// Bearish OB: bullish candle immediately before a bearish move
bearishOB = close[1] > open[1] and close < open

if bullishOB
    box.new(bar_index[1], low[1], bar_index + lookback, high[1],
            bgcolor=color.new(color.green, 80),
            border_color=color.new(color.green, 60),
            border_width=1)

if bearishOB
    box.new(bar_index[1], low[1], bar_index + lookback, high[1],
            bgcolor=color.new(color.red, 80),
            border_color=color.new(color.red, 60),
            border_width=1)
`
}

func genLiquiditySweep() string {
	return `
//@version=5
indicator("ICT Liquidity Sweep", overlay=true)

length = input.int(20, "Swing Length", minval=5)

swingHigh = ta.highest(high, length)[1]
swingLow  = ta.lowest(low,  length)[1]

// Sweep high: wick above prior swing high but closes below it
sweepHigh = high > swingHigh and close < swingHigh
// Sweep low:  wick below prior swing low but closes above it
sweepLow  = low  < swingLow  and close > swingLow

plotshape(sweepHigh, "SSL Sweep", style=shape.triangledown,
          location=location.abovebar, color=color.red,   size=size.small)
plotshape(sweepLow,  "BSL Sweep", style=shape.triangleup,
          location=location.belowbar, color=color.green, size=size.small)

plot(swingHigh, "Swing High", color=color.new(color.red,   70), style=plot.style_stepline)
plot(swingLow,  "Swing Low",  color=color.new(color.green, 70), style=plot.style_stepline)
`
}

func genRSIOBOS() string {
	return `
//@version=5
indicator("RSI Overbought / Oversold", overlay=true)

rsiLen = input.int(14,   "RSI Length",        minval=2)
obLevel = input.float(70, "Overbought Level",  minval=50, maxval=100)
osLevel = input.float(30, "Oversold Level",    minval=0,  maxval=50)

rsi = ta.rsi(close, rsiLen)

obSignal = rsi >= obLevel
osSignal = rsi <= osLevel

plotshape(osSignal, "Oversold",   style=shape.triangleup,   location=location.belowbar, color=color.green, size=size.small)
plotshape(obSignal, "Overbought", style=shape.triangledown, location=location.abovebar, color=color.red,   size=size.small)
`
}

func genRSIDivergence() string {
	return `
//@version=5
indicator("RSI Divergence", overlay=true)

rsiLen   = input.int(14, "RSI Length",    minval=2)
pivotLen = input.int(5,  "Pivot Length",  minval=2)

rsi = ta.rsi(close, rsiLen)

priceHigh = ta.pivothigh(high,  pivotLen, pivotLen)
priceLow  = ta.pivotlow(low,   pivotLen, pivotLen)
rsiHigh   = ta.pivothigh(rsi,  pivotLen, pivotLen)
rsiLow    = ta.pivotlow(rsi,   pivotLen, pivotLen)

// Bearish: price makes higher high, RSI makes lower high
bearDiv = not na(priceHigh) and not na(rsiHigh) and
          high[pivotLen] > high[pivotLen * 2] and rsi[pivotLen] < rsi[pivotLen * 2]

// Bullish: price makes lower low, RSI makes higher low
bullDiv = not na(priceLow) and not na(rsiLow) and
          low[pivotLen] < low[pivotLen * 2] and rsi[pivotLen] > rsi[pivotLen * 2]

plotshape(bullDiv, "Bullish Div", style=shape.triangleup,   location=location.belowbar, color=color.green, size=size.normal)
plotshape(bearDiv, "Bearish Div", style=shape.triangledown, location=location.abovebar, color=color.red,   size=size.normal)
`
}

func genSRBreakout() string {
	return `
//@version=5
indicator("Support / Resistance Breakout", overlay=true)

length = input.int(20, "Pivot Length", minval=5)

pivH = ta.pivothigh(high, length, length)
pivL = ta.pivotlow(low,  length, length)

var float resistance = na
var float support    = na

if not na(pivH)
    resistance := pivH
if not na(pivL)
    support := pivL

breakoutUp   = not na(resistance) and close[1] < resistance and close > resistance
breakoutDown = not na(support)    and close[1] > support    and close < support

plotshape(breakoutUp,   "R Breakout", style=shape.triangleup,   location=location.belowbar, color=color.green, size=size.small)
plotshape(breakoutDown, "S Breakdown", style=shape.triangledown, location=location.abovebar, color=color.red,   size=size.small)

plot(resistance, "Resistance", color=color.new(color.red,   40), style=plot.style_linebr, linewidth=1)
plot(support,    "Support",    color=color.new(color.green, 40), style=plot.style_linebr, linewidth=1)
`
}

func genWyckoffAccumulation() string {
	return `
//@version=5
indicator("Wyckoff Accumulation (Simplified)", overlay=false)

volLen   = input.int(20, "Volume MA Length", minval=5)
priceLen = input.int(20, "Price Range Length", minval=5)

volMA      = ta.sma(volume, volLen)
highest    = ta.highest(high, priceLen)
lowest     = ta.lowest(low,  priceLen)
priceRange = highest - lowest
rangeMA    = ta.sma(priceRange, priceLen)

// Accumulation cues: narrow range + below-average volume
narrowRange = priceRange < rangeMA * 0.8
lowVol      = volume < volMA * 0.8
// Spring: brief dip below range low then close above
spring      = low < lowest[1] and close > open

accSignal = narrowRange and lowVol and spring

plotshape(accSignal, "Accumulation", style=shape.triangleup,
          location=location.bottom, color=color.green, size=size.small)

plot(volMA, "Vol MA", color=color.blue, linewidth=1)
plot(volume, "Volume", style=plot.style_histogram,
     color=volume > volMA ? color.new(color.green, 40) : color.new(color.red, 40))
`
}

func genWyckoffDistribution() string {
	return `
//@version=5
indicator("Wyckoff Distribution (Simplified)", overlay=false)

volLen   = input.int(20, "Volume MA Length", minval=5)
priceLen = input.int(20, "Price Range Length", minval=5)

volMA      = ta.sma(volume, volLen)
highest    = ta.highest(high, priceLen)
lowest     = ta.lowest(low,  priceLen)
priceRange = highest - lowest
rangeMA    = ta.sma(priceRange, priceLen)

// Distribution cues: narrow range + below-average volume
narrowRange = priceRange < rangeMA * 0.8
lowVol      = volume < volMA * 0.8
// UTAD: brief push above range high then close below
utad        = high > highest[1] and close < open

distSignal = narrowRange and lowVol and utad

plotshape(distSignal, "Distribution", style=shape.triangledown,
          location=location.top, color=color.red, size=size.small)

plot(volMA, "Vol MA", color=color.blue, linewidth=1)
plot(volume, "Volume", style=plot.style_histogram,
     color=volume > volMA ? color.new(color.green, 40) : color.new(color.red, 40))
`
}

func genFibonacci() string {
	return `
//@version=5
indicator("Fibonacci Confluence", overlay=true)

length = input.int(50, "Swing Length", minval=10)

swingHigh = ta.highest(high, length)
swingLow  = ta.lowest(low,  length)
diff      = swingHigh - swingLow

fib236 = swingLow + diff * 0.236
fib382 = swingLow + diff * 0.382
fib500 = swingLow + diff * 0.500
fib618 = swingLow + diff * 0.618
fib786 = swingLow + diff * 0.786

plot(fib236, "23.6%", color=color.new(color.yellow, 30), linewidth=1)
plot(fib382, "38.2%", color=color.new(color.orange, 30), linewidth=1)
plot(fib500, "50.0%", color=color.new(color.white,  30), linewidth=1)
plot(fib618, "61.8%", color=color.new(color.orange, 30), linewidth=2)
plot(fib786, "78.6%", color=color.new(color.yellow, 30), linewidth=1)

// Signal: price near golden pocket (61.8%) or 38.2%
nearGolden = math.abs(close - fib618) / close < 0.005 or
             math.abs(close - fib382) / close < 0.005
plotshape(nearGolden, "Fib Confluence", style=shape.diamond,
          location=location.belowbar, color=color.purple, size=size.tiny)
`
}
