// Package paper implements a real-time paper trading simulator.
// Signals generated by the rule engine trigger virtual positions that are
// tracked against live price data until TP or SL is hit.
package paper

import (
	"sync"
	"time"

	"github.com/rs/zerolog"

	"github.com/Ju571nK/Chatter/pkg/models"
)

// PaperPosition represents one virtual trade.
type PaperPosition struct {
	ID         int64      `json:"id"`
	Symbol     string     `json:"symbol"`
	Timeframe  string     `json:"timeframe"`
	Rule       string     `json:"rule"`
	Direction  string     `json:"direction"`  // "LONG" | "SHORT"
	EntryPrice float64    `json:"entry_price"`
	TP         float64    `json:"tp"`
	SL         float64    `json:"sl"`
	EntryTime  time.Time  `json:"entry_time"`
	ExitPrice  float64    `json:"exit_price"`
	ExitTime   *time.Time `json:"exit_time"`
	Status     string     `json:"status"` // "OPEN"|"CLOSED_TP"|"CLOSED_SL"|"CLOSED_MANUAL"
	PnLPct     float64    `json:"pnl_pct"`
}

// PaperSummary holds aggregated paper trading statistics.
type PaperSummary struct {
	OpenPositions int     `json:"open_positions"`
	ClosedTrades  int     `json:"closed_trades"`
	Wins          int     `json:"wins"`
	Losses        int     `json:"losses"`
	WinRate       float64 `json:"win_rate"`
	TotalPnLPct   float64 `json:"total_pnl_pct"`
	AvgWinPct     float64 `json:"avg_win_pct"`
	AvgLossPct    float64 `json:"avg_loss_pct"`
}

// Store is the persistence interface for paper positions.
// *storage.DB satisfies this interface.
type Store interface {
	SavePaperPosition(pos PaperPosition) (int64, error)
	GetOpenPositions(symbol string) ([]PaperPosition, error)
	GetAllOpenPositions() ([]PaperPosition, error)
	ClosePaperPosition(id int64, exitPrice float64, status string, pnlPct float64) error
	GetClosedPositions(limit int) ([]PaperPosition, error)
}

// Trader manages virtual paper positions driven by live rule engine signals.
type Trader struct {
	store Store
	log   zerolog.Logger
	mu    sync.Mutex
}

// New creates a Trader backed by the given store.
func New(store Store, log zerolog.Logger) *Trader {
	return &Trader{store: store, log: log}
}

// OnSignals opens new paper positions for LONG/SHORT signals that have
// EntryPrice set. At most one OPEN position per symbol is kept.
func (t *Trader) OnSignals(signals []models.Signal) {
	t.mu.Lock()
	defer t.mu.Unlock()

	// Collect symbols that already have open positions to avoid duplicates.
	openBySymbol := map[string]bool{}
	for _, sig := range signals {
		if sig.EntryPrice <= 0 || sig.Direction == "NEUTRAL" {
			continue
		}
		if openBySymbol[sig.Symbol] {
			continue
		}
		existing, err := t.store.GetOpenPositions(sig.Symbol)
		if err != nil || len(existing) > 0 {
			openBySymbol[sig.Symbol] = true
			continue
		}

		pos := PaperPosition{
			Symbol:     sig.Symbol,
			Timeframe:  sig.Timeframe,
			Rule:       sig.Rule,
			Direction:  sig.Direction,
			EntryPrice: sig.EntryPrice,
			TP:         sig.TP,
			SL:         sig.SL,
			EntryTime:  sig.CreatedAt,
			Status:     "OPEN",
		}
		id, err := t.store.SavePaperPosition(pos)
		if err != nil {
			t.log.Error().Err(err).Str("symbol", sig.Symbol).Msg("[Paper] 포지션 저장 실패")
			continue
		}
		openBySymbol[sig.Symbol] = true
		t.log.Info().
			Int64("id", id).
			Str("symbol", sig.Symbol).
			Str("direction", sig.Direction).
			Str("rule", sig.Rule).
			Float64("entry", sig.EntryPrice).
			Float64("tp", sig.TP).
			Float64("sl", sig.SL).
			Msg("[Paper] 포지션 오픈")
	}
}

// CheckPositions scans open positions for the given symbol against the
// most recent OHLCV bars. Closes any positions where TP or SL was hit.
//
// allBars is expected in DESC order (index 0 = most recent bar).
func (t *Trader) CheckPositions(sym string, allBars map[string][]models.OHLCV) {
	t.mu.Lock()
	defer t.mu.Unlock()

	positions, err := t.store.GetOpenPositions(sym)
	if err != nil || len(positions) == 0 {
		return
	}

	for _, pos := range positions {
		bars, ok := allBars[pos.Timeframe]
		if !ok || len(bars) == 0 {
			// Fall back to 1H as the most granular available TF.
			bars = allBars["1H"]
		}
		if len(bars) == 0 {
			continue
		}

		// bars is DESC; iterate newest→oldest, but only check bars after entry.
		for _, bar := range bars {
			if !bar.OpenTime.After(pos.EntryTime) {
				break // older than entry — stop
			}
			status, exitPrice, hit := checkLevel(pos, bar)
			if !hit {
				continue
			}
			var pnlPct float64
			if pos.Direction == "LONG" {
				pnlPct = (exitPrice - pos.EntryPrice) / pos.EntryPrice * 100
			} else {
				pnlPct = (pos.EntryPrice - exitPrice) / pos.EntryPrice * 100
			}
			if err := t.store.ClosePaperPosition(pos.ID, exitPrice, status, pnlPct); err != nil {
				t.log.Error().Err(err).Int64("id", pos.ID).Msg("[Paper] 포지션 청산 실패")
				continue
			}
			t.log.Info().
				Int64("id", pos.ID).
				Str("symbol", pos.Symbol).
				Str("status", status).
				Float64("pnl_pct", pnlPct).
				Msg("[Paper] 포지션 청산")
			break // position closed
		}
	}
}

// checkLevel returns whether TP or SL was hit in bar and which one.
func checkLevel(pos PaperPosition, bar models.OHLCV) (status string, exitPrice float64, hit bool) {
	if pos.Direction == "LONG" {
		if bar.High >= pos.TP {
			return "CLOSED_TP", pos.TP, true
		}
		if bar.Low <= pos.SL {
			return "CLOSED_SL", pos.SL, true
		}
	} else {
		if bar.Low <= pos.TP {
			return "CLOSED_TP", pos.TP, true
		}
		if bar.High >= pos.SL {
			return "CLOSED_SL", pos.SL, true
		}
	}
	return "", 0, false
}

// Summary computes aggregated stats from all closed positions.
func Summary(closed []PaperPosition, openCount int) PaperSummary {
	s := PaperSummary{OpenPositions: openCount, ClosedTrades: len(closed)}
	if len(closed) == 0 {
		return s
	}
	var winPnL, lossPnL []float64
	for _, p := range closed {
		s.TotalPnLPct += p.PnLPct
		if p.PnLPct > 0 {
			s.Wins++
			winPnL = append(winPnL, p.PnLPct)
		} else {
			s.Losses++
			lossPnL = append(lossPnL, p.PnLPct)
		}
	}
	if s.ClosedTrades > 0 {
		s.WinRate = float64(s.Wins) / float64(s.ClosedTrades)
	}
	s.AvgWinPct = mean(winPnL)
	s.AvgLossPct = mean(lossPnL)
	return s
}

func mean(xs []float64) float64 {
	if len(xs) == 0 {
		return 0
	}
	sum := 0.0
	for _, x := range xs {
		sum += x
	}
	return sum / float64(len(xs))
}
