// Package paper implements a real-time paper trading simulator.
// Signals generated by the rule engine trigger virtual positions that are
// tracked against live price data until TP or SL is hit.
package paper

import (
	"sync"
	"time"

	"github.com/rs/zerolog"

	"github.com/Ju571nK/Chatter/internal/market"
	"github.com/Ju571nK/Chatter/pkg/models"
)

// PaperPosition represents one virtual trade.
type PaperPosition struct {
	ID                  int64             `json:"id"`
	Symbol              string            `json:"symbol"`
	Timeframe           string            `json:"timeframe"`
	Rule                string            `json:"rule"`
	Direction           string            `json:"direction"` // "LONG" | "SHORT"
	EntryPrice          float64           `json:"entry_price"`
	EntryExecutionPrice float64           `json:"entry_execution_price,omitempty"`
	TP                  float64           `json:"tp"`
	SL                  float64           `json:"sl"`
	EntryTime           time.Time         `json:"entry_time"`
	ExitPrice           float64           `json:"exit_price"`
	ExitExecutionPrice  float64           `json:"exit_execution_price,omitempty"`
	PriceBasis          string            `json:"price_basis,omitempty"`
	ExitTime            *time.Time        `json:"exit_time"`
	Status              string            `json:"status"` // "OPEN"|"CLOSED_TP"|"CLOSED_SL"|"CLOSED_MANUAL"
	PnLPct              float64           `json:"pnl_pct"`
	AssetClass          models.AssetClass `json:"asset_class,omitempty"`
	PipSize             float64           `json:"pip_size,omitempty"`
	SpreadPips          float64           `json:"spread_pips,omitempty"`
	PnLPips             float64           `json:"pnl_pips,omitempty"`
	DataProvider        string            `json:"data_provider,omitempty"`
	ProviderSymbol      string            `json:"provider_symbol,omitempty"`
	SourceIdentity      string            `json:"source_identity,omitempty"`
	DataProxy           bool              `json:"data_proxy,omitempty"`
	Suspended           bool              `json:"suspended,omitempty"`
	SuspensionReason    string            `json:"suspension_reason,omitempty"`
}

// PaperSummary holds aggregated paper trading statistics.
type PaperSummary struct {
	OpenPositions int     `json:"open_positions"`
	ClosedTrades  int     `json:"closed_trades"`
	Wins          int     `json:"wins"`
	Losses        int     `json:"losses"`
	WinRate       float64 `json:"win_rate"`
	TotalPnLPct   float64 `json:"total_pnl_pct"`
	AvgWinPct     float64 `json:"avg_win_pct"`
	AvgLossPct    float64 `json:"avg_loss_pct"`
	AvgRR         float64 `json:"avg_rr"`
	ProfitFactor  float64 `json:"profit_factor"`
	NetPips       float64 `json:"net_pips,omitempty"`
	AvgPips       float64 `json:"avg_pips,omitempty"`
}

// Store is the persistence interface for paper positions.
// *storage.DB satisfies this interface.
type Store interface {
	SavePaperPosition(pos PaperPosition) (int64, error)
	GetOpenPositions(symbol string) ([]PaperPosition, error)
	GetAllOpenPositions() ([]PaperPosition, error)
	ClosePaperPosition(id int64, exitPrice float64, status string, pnlPct float64) error
	GetClosedPositions(limit int) ([]PaperPosition, error)
}

// Trader manages virtual paper positions driven by live rule engine signals.
type Trader struct {
	store        Store
	log          zerolog.Logger
	mu           sync.Mutex
	forexSources map[string]string
}

// New creates a Trader backed by the given store.
func New(store Store, log zerolog.Logger) *Trader {
	return &Trader{store: store, log: log}
}

func (t *Trader) SetForexSources(sources map[string]string) {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.forexSources = sources
}

// OnSignals opens new paper positions for LONG/SHORT signals that have
// EntryPrice set. At most one OPEN position per symbol is kept.
func (t *Trader) OnSignals(signals []models.Signal) {
	t.mu.Lock()
	defer t.mu.Unlock()

	// Collect symbols that already have open positions to avoid duplicates.
	openBySymbol := map[string]bool{}
	for _, sig := range signals {
		if sig.EntryPrice <= 0 || sig.Direction == "NEUTRAL" {
			continue
		}
		if openBySymbol[sig.Symbol] {
			continue
		}
		existing, err := t.store.GetOpenPositions(sig.Symbol)
		if err != nil || len(existing) > 0 {
			openBySymbol[sig.Symbol] = true
			continue
		}

		pos := PaperPosition{
			Symbol:         sig.Symbol,
			Timeframe:      sig.Timeframe,
			Rule:           sig.Rule,
			Direction:      sig.Direction,
			EntryPrice:     sig.EntryPrice,
			PriceBasis:     "mid",
			TP:             sig.TP,
			SL:             sig.SL,
			EntryTime:      sig.CreatedAt,
			Status:         "OPEN",
			AssetClass:     sig.AssetClass,
			DataProvider:   sig.DataProvider,
			ProviderSymbol: sig.ProviderSymbol,
			SourceIdentity: sig.SourceIdentity,
			DataProxy:      sig.DataProxy,
		}
		if sig.AssetClass == models.AssetForex {
			if sig.SourceIdentity == "" || (t.forexSources != nil && t.forexSources[sig.Symbol] != sig.SourceIdentity) {
				continue
			}
			spec := market.Instrument(sig.Symbol)
			pos.PipSize, pos.SpreadPips = spec.PipSize, spec.DefaultSpreadPips
			if sig.SpreadPipsSet || sig.SpreadPips > 0 {
				pos.SpreadPips = sig.SpreadPips
			}
			pos.EntryExecutionPrice = pos.EntryPrice + pos.SpreadPips*pos.PipSize/2
			if pos.Direction == "SHORT" {
				pos.EntryExecutionPrice = pos.EntryPrice - pos.SpreadPips*pos.PipSize/2
			}
		}
		id, err := t.store.SavePaperPosition(pos)
		if err != nil {
			t.log.Error().Err(err).Str("symbol", sig.Symbol).Msg("[Paper] position save failed")
			continue
		}
		openBySymbol[sig.Symbol] = true
		t.log.Info().
			Int64("id", id).
			Str("symbol", sig.Symbol).
			Str("direction", sig.Direction).
			Str("rule", sig.Rule).
			Float64("entry", sig.EntryPrice).
			Float64("tp", sig.TP).
			Float64("sl", sig.SL).
			Msg("[Paper] position opened")
	}
}

// CheckPositions scans open positions for the given symbol against the
// most recent OHLCV bars. Closes any positions where TP or SL was hit.
//
// allBars is expected in DESC order (index 0 = most recent bar).
func (t *Trader) CheckPositions(sym string, allBars map[string][]models.OHLCV) {
	t.mu.Lock()
	defer t.mu.Unlock()

	positions, err := t.store.GetOpenPositions(sym)
	if err != nil || len(positions) == 0 {
		return
	}

	for _, pos := range positions {
		if pos.Suspended || (pos.AssetClass == models.AssetForex && (pos.SourceIdentity == "" || t.forexSources[pos.Symbol] != pos.SourceIdentity)) {
			continue
		}
		bars, ok := allBars[pos.Timeframe]
		if !ok || len(bars) == 0 {
			// Fall back to 1H as the most granular available TF.
			bars = allBars["1H"]
		}
		if len(bars) == 0 {
			continue
		}

		// bars is DESC; inspect oldest first so the first exit after entry wins.
		// A candle that opened before (or at) the signal is excluded in full:
		// its high/low may have occurred before entry and cannot safely trigger
		// an exit without finer-grained quotes.
		for i := len(bars) - 1; i >= 0; i-- {
			bar := bars[i]
			if pos.AssetClass == models.AssetForex {
				expected := "yahoo_fx"
				if pos.DataProvider == "oanda" {
					expected = "oanda"
				}
				if pos.DataProvider == "" || bar.Source != expected {
					continue
				}
			}
			if !bar.OpenTime.After(pos.EntryTime) {
				continue
			}
			status, exitPrice, hit := checkLevel(pos, bar)
			if !hit {
				continue
			}
			var pnlPct, pnlPips float64
			if pos.Direction == "LONG" {
				pnlPct = (exitPrice - pos.EntryPrice) / pos.EntryPrice * 100
			} else {
				pnlPct = (pos.EntryPrice - exitPrice) / pos.EntryPrice * 100
			}
			if pos.PipSize > 0 {
				pos.ExitExecutionPrice = exitPrice - pos.SpreadPips*pos.PipSize/2
				if pos.Direction == "SHORT" {
					pos.ExitExecutionPrice = exitPrice + pos.SpreadPips*pos.PipSize/2
				}
				pnlPips = pnlPct/100*pos.EntryPrice/pos.PipSize - pos.SpreadPips
				entryExecution := pos.EntryPrice + pos.SpreadPips*pos.PipSize/2
				if pos.Direction == "SHORT" {
					entryExecution = pos.EntryPrice - pos.SpreadPips*pos.PipSize/2
				}
				pnlPct = pnlPips * pos.PipSize / entryExecution * 100
			}
			var closeErr error
			if store, ok := t.store.(interface {
				ClosePaperPositionWithPips(int64, float64, string, float64, float64) error
			}); ok {
				closeErr = store.ClosePaperPositionWithPips(pos.ID, exitPrice, status, pnlPct, pnlPips)
			} else {
				closeErr = t.store.ClosePaperPosition(pos.ID, exitPrice, status, pnlPct)
			}
			if closeErr != nil {
				t.log.Error().Err(closeErr).Int64("id", pos.ID).Msg("[Paper] position close failed")
				continue
			}
			t.log.Info().
				Int64("id", pos.ID).
				Str("symbol", pos.Symbol).
				Str("status", status).
				Float64("pnl_pct", pnlPct).
				Msg("[Paper] position closed")
			break // position closed
		}
	}
}

// checkLevel returns whether TP or SL was hit in bar and which one.
func checkLevel(pos PaperPosition, bar models.OHLCV) (status string, exitPrice float64, hit bool) {
	if pos.Direction == "LONG" {
		if bar.High >= pos.TP {
			return "CLOSED_TP", pos.TP, true
		}
		if bar.Low <= pos.SL {
			return "CLOSED_SL", pos.SL, true
		}
	} else {
		if bar.Low <= pos.TP {
			return "CLOSED_TP", pos.TP, true
		}
		if bar.High >= pos.SL {
			return "CLOSED_SL", pos.SL, true
		}
	}
	return "", 0, false
}

// Summary computes aggregated stats from all closed positions.
func Summary(closed []PaperPosition, openCount int) PaperSummary {
	s := PaperSummary{OpenPositions: openCount, ClosedTrades: len(closed)}
	if len(closed) == 0 {
		return s
	}
	var winPnL, lossPnL []float64
	var fxTrades int
	for _, p := range closed {
		s.TotalPnLPct += p.PnLPct
		if p.PipSize > 0 {
			fxTrades++
			s.NetPips += p.PnLPips
		}
		if p.PnLPct > 0 {
			s.Wins++
			winPnL = append(winPnL, p.PnLPct)
		} else {
			s.Losses++
			lossPnL = append(lossPnL, p.PnLPct)
		}
	}
	if s.ClosedTrades > 0 {
		s.WinRate = float64(s.Wins) / float64(s.ClosedTrades)
	}
	s.AvgWinPct = mean(winPnL)
	s.AvgLossPct = mean(lossPnL)
	if fxTrades > 0 {
		s.AvgPips = s.NetPips / float64(fxTrades)
	}
	if s.AvgLossPct < 0 {
		s.AvgRR = s.AvgWinPct / -s.AvgLossPct
	}
	var grossWin, grossLoss float64
	for _, p := range closed {
		if p.PnLPct > 0 {
			grossWin += p.PnLPct
		} else {
			grossLoss -= p.PnLPct
		}
	}
	if grossLoss > 0 {
		s.ProfitFactor = grossWin / grossLoss
	} else if grossWin > 0 {
		s.ProfitFactor = 99.99
	}
	return s
}

func mean(xs []float64) float64 {
	if len(xs) == 0 {
		return 0
	}
	sum := 0.0
	for _, x := range xs {
		sum += x
	}
	return sum / float64(len(xs))
}
